import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import * as api from '@/features/community/api/community-api'
import { useAuthStore } from '@/features/auth/stores/auth-store'
import { commentFixture, postFixture, reviewFixture } from '@/test/fixtures/community'
import { mockRouter } from '@/test/mocks/next-navigation'
import type { PostPage } from '@/features/community/types/community'
import CommunityBoard from './community-board'
import { CommunityPhoto } from './community-shared'

vi.mock('@/features/community/api/community-api')

function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (reason: unknown) => void
  const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no })
  return { promise, resolve, reject }
}

beforeEach(() => {
  vi.resetAllMocks()
  Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', { configurable: true, value: vi.fn() })
  useAuthStore.setState({ status: 'authenticated', sessionEpoch: 0 })
  vi.mocked(api.fetchPosts).mockResolvedValue({ posts: [postFixture], nextCursor: null })
  vi.mocked(api.fetchPost).mockResolvedValue(postFixture)
  vi.mocked(api.fetchMyBookmarks).mockResolvedValue([])
  vi.mocked(api.fetchMyPosts).mockResolvedValue([])
  vi.mocked(api.fetchMyReviews).mockResolvedValue([reviewFixture])
  vi.mocked(api.fetchPlaceReviews).mockResolvedValue([reviewFixture])
  vi.mocked(api.createComment).mockResolvedValue(commentFixture)
})
afterEach(cleanup)

describe('live community board', () => {
  it('loads popular/latest sorting and routes real IDs to detail', async () => {
    const user = userEvent.setup()
    render(<CommunityBoard />)
    await user.click(await screen.findByRole('button', { name: new RegExp(postFixture.title) }))
    expect(mockRouter.push).toHaveBeenCalledWith('/community?post=post-1')
    await user.click(screen.getByRole('button', { name: '자유게시판' }))
    await waitFor(() => expect(api.fetchPosts).toHaveBeenLastCalledWith('latest', undefined, expect.any(AbortSignal)))
  })
  it('ignores delayed results when changing tabs', async () => {
    const pending = deferred<PostPage>()
    vi.mocked(api.fetchPosts).mockReturnValueOnce(pending.promise).mockResolvedValue({ posts: [{ ...postFixture, title: '최신 글' }], nextCursor: null })
    render(<CommunityBoard />)
    const signal = vi.mocked(api.fetchPosts).mock.calls[0][2]
    fireEvent.click(screen.getByRole('button', { name: '자유게시판' }))
    expect(await screen.findByText('최신 글')).toBeInTheDocument()
    await act(async () => pending.resolve({ posts: [postFixture], nextCursor: null }))
    expect(signal?.aborted).toBe(true)
    expect(screen.queryByText(postFixture.title)).not.toBeInTheDocument()
  })
  it('keeps loaded posts after a page failure and retries the same cursor without duplicates', async () => {
    vi.mocked(api.fetchPosts).mockResolvedValueOnce({ posts: [postFixture], nextCursor: 'opaque~cursor' }).mockRejectedValueOnce({ type: 'network' }).mockResolvedValueOnce({ posts: [postFixture, { ...postFixture, id: 'post-2', title: '다음 글' }], nextCursor: null })
    const user = userEvent.setup()
    render(<CommunityBoard />)
    await user.click(await screen.findByRole('button', { name: '더 불러오기' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('인터넷 연결')
    expect(screen.getByText(postFixture.title)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '더 불러오기 다시 시도' }))
    expect(await screen.findByText('다음 글')).toBeInTheDocument()
    expect(screen.getAllByText(postFixture.title)).toHaveLength(1)
    expect(screen.queryByRole('button', { name: '더 불러오기' })).not.toBeInTheDocument()
    expect(api.fetchPosts).toHaveBeenLastCalledWith('popular', 'opaque~cursor', expect.any(AbortSignal))
  })
  it('shows empty feed and handles first-page recovery', async () => {
    vi.mocked(api.fetchPosts).mockRejectedValueOnce({ type: 'server' }).mockResolvedValueOnce({ posts: [], nextCursor: null })
    const user = userEvent.setup()
    render(<CommunityBoard />)
    await user.click(await screen.findByRole('button', { name: '다시 시도' }))
    expect(await screen.findByText('아직 등록된 게시글이 없어요.')).toBeInTheDocument()
  })
  it('reads a direct detail ID outside the initial feed and tracks subsequent URL changes', async () => {
    const { rerender } = render(<CommunityBoard initialPostId="server-id" />)
    expect(await screen.findByRole('heading', { name: postFixture.title })).toBeInTheDocument()
    expect(api.fetchPost).toHaveBeenCalledWith('server-id', expect.any(AbortSignal))
    expect(api.fetchPosts).not.toHaveBeenCalled()
    vi.mocked(api.fetchPost).mockResolvedValueOnce({ ...postFixture, id: 'post-2', title: '다른 상세' })
    rerender(<CommunityBoard initialPostId="post-2" />)
    expect(await screen.findByRole('heading', { name: '다른 상세' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '뒤로가기' }))
    expect(mockRouter.replace).toHaveBeenCalledWith('/community')
  })
  it('does not fall back to fixture content for deleted detail', async () => {
    vi.mocked(api.fetchPost).mockRejectedValue({ type: 'not-found' })
    render(<CommunityBoard initialPostId="deleted" />)
    expect(await screen.findByRole('alert')).toHaveTextContent('찾을 수 없는')
    expect(screen.queryByText(postFixture.title)).not.toBeInTheDocument()
  })
  it('does not guess bookmark state or ownership when metadata reads fail', async () => {
    vi.mocked(api.fetchMyBookmarks).mockRejectedValue({ type: 'network' })
    vi.mocked(api.fetchMyPosts).mockRejectedValue({ type: 'network' })
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    expect(await screen.findByRole('button', { name: '북마크' })).toBeDisabled()
    await user.click(screen.getByRole('button', { name: '더보기' }))
    expect(screen.queryByRole('button', { name: '게시글 삭제' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '내 게시글 다시 확인' })).toBeInTheDocument()
  })
  it('hydrates bookmarks and does not toggle on failure', async () => {
    vi.mocked(api.fetchMyBookmarks).mockResolvedValue([postFixture])
    vi.mocked(api.setPostBookmark).mockRejectedValueOnce({ type: 'server' })
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    await user.click(await screen.findByRole('button', { name: '북마크 취소' }))
    expect(await screen.findByRole('alert')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '북마크 취소' })).toHaveAttribute('aria-pressed', 'true')
    expect(api.setPostBookmark).toHaveBeenCalledWith('post-1', false)
  })
  it('preserves comments on failure and prevents duplicate submission', async () => {
    vi.mocked(api.createComment).mockRejectedValueOnce({ type: 'unauthorized' })
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    await user.type(await screen.findByRole('textbox', { name: '댓글 내용' }), '즐거운 여행이네요')
    await user.click(screen.getByRole('button', { name: '댓글 전송' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('로그인')
    expect(screen.getByRole('textbox', { name: '댓글 내용' })).toHaveValue('즐거운 여행이네요')
    const pending = deferred<typeof commentFixture>()
    vi.mocked(api.createComment).mockReturnValueOnce(pending.promise)
    fireEvent.click(screen.getByRole('button', { name: '댓글 전송' }))
    fireEvent.click(screen.getByRole('button', { name: '댓글 전송' }))
    expect(api.createComment).toHaveBeenCalledTimes(2)
    await act(async () => pending.resolve(commentFixture))
    expect(await screen.findByText(commentFixture.content)).toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: '댓글 내용' })).toHaveValue('')
    expect(screen.getByRole('heading', { name: '댓글 3' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '댓글 삭제' }))
    await user.click(screen.getByRole('button', { name: '삭제 확인' }))
    await waitFor(() => expect(screen.queryByText(commentFixture.content)).not.toBeInTheDocument())
    expect(screen.getByRole('heading', { name: '댓글 2' })).toBeInTheDocument()
  })
  it('does not retain private detail or drafts when the session changes', async () => {
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    await user.type(await screen.findByRole('textbox', { name: '댓글 내용' }), '이전 세션 초안')
    vi.mocked(api.fetchPost).mockReturnValue(new Promise(() => {}))
    act(() => useAuthStore.setState({ sessionEpoch: 1 }))
    expect(screen.queryByDisplayValue('이전 세션 초안')).not.toBeInTheDocument()
    expect(screen.queryByText(postFixture.title)).not.toBeInTheDocument()
  })
  it('does not issue a recommendation follow-up request after leaving the detail view', async () => {
    const pending = deferred<void>()
    vi.mocked(api.setPostRecommendation).mockReturnValue(pending.promise)
    const user = userEvent.setup()
    const { unmount } = render(<CommunityBoard initialPostId="post-1" />)
    await user.click(await screen.findByRole('button', { name: '게시글 추천' }))
    unmount()
    act(() => useAuthStore.setState({ sessionEpoch: 1, status: 'unauthenticated' }))
    await act(async () => pending.resolve())
    expect(api.fetchPost).toHaveBeenCalledTimes(1)
    expect(api.setPostRecommendation).toHaveBeenCalledTimes(1)
  })
  it('retains the actual parent ordering when replying after another root comment', async () => {
    vi.mocked(api.createComment).mockResolvedValueOnce({ ...commentFixture, id: 'A', content: '첫 댓글' }).mockResolvedValueOnce({ ...commentFixture, id: 'B', content: '둘째 댓글' }).mockResolvedValueOnce({ ...commentFixture, id: 'A-reply', parentCommentId: 'A', content: '첫 댓글의 답글', depth: 1 })
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    const input = await screen.findByRole('textbox', { name: '댓글 내용' })
    for (const text of ['첫 댓글', '둘째 댓글']) {
      await user.type(input, text)
      await user.click(screen.getByRole('button', { name: '댓글 전송' }))
      await screen.findByText(text)
    }
    await user.click(screen.getAllByRole('button', { name: '답글' })[0])
    await user.type(input, '첫 댓글의 답글')
    await user.click(screen.getByRole('button', { name: '댓글 전송' }))
    await screen.findByText('첫 댓글의 답글')
    expect(api.createComment).toHaveBeenLastCalledWith('post-1', '첫 댓글의 답글', 'A')
    const reply = screen.getByText('첫 댓글의 답글')
    const secondRoot = screen.getByText('둘째 댓글')
    expect(reply.compareDocumentPosition(secondRoot) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  })
  it('opens action panels visibly and keeps the comment form outside the scroll body', async () => {
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    await user.click(await screen.findByRole('button', { name: '신고' }))
    expect(HTMLElement.prototype.scrollIntoView).toHaveBeenCalled()
    expect(screen.getByLabelText('게시글 작업')).toHaveFocus()
    expect(screen.getByRole('textbox', { name: '댓글 내용' }).closest('.overflow-y-auto')).toBeNull()
  })
  it('cancels own review deletion and retains the review on failed delete before retry', async () => {
    vi.mocked(api.deleteReview).mockRejectedValueOnce({ type: 'forbidden' }).mockResolvedValueOnce(undefined)
    const user = userEvent.setup()
    render(<CommunityBoard />)
    await user.click(screen.getByRole('button', { name: '여행 리뷰' }))
    await user.click(await screen.findByRole('button', { name: '리뷰 삭제' }))
    await user.click(screen.getByRole('button', { name: '취소' }))
    expect(api.deleteReview).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: '리뷰 삭제' }))
    await user.click(screen.getByRole('button', { name: '리뷰 삭제 확인' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('권한')
    expect(screen.getByText(reviewFixture.contents)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '리뷰 삭제 확인' }))
    expect(await screen.findByText('아직 작성한 여행 리뷰가 없어요.')).toBeInTheDocument()
  })
  it('shows edit/delete only for own IDs and waits for successful edit response', async () => {
    vi.mocked(api.fetchMyPosts).mockResolvedValue([postFixture])
    vi.mocked(api.updatePost).mockResolvedValue({ ...postFixture, title: '수정 완료' })
    const user = userEvent.setup()
    render(<CommunityBoard initialPostId="post-1" />)
    await user.click(await screen.findByRole('button', { name: '더보기' }))
    await user.click(await screen.findByRole('button', { name: '게시글 수정' }))
    await user.clear(screen.getByRole('textbox', { name: '게시글 제목' }))
    await user.type(screen.getByRole('textbox', { name: '게시글 제목' }), '수정 완료')
    await user.click(screen.getByRole('button', { name: '수정 저장' }))
    expect(await screen.findByRole('heading', { name: '수정 완료' })).toBeInTheDocument()
    expect(api.updatePost).toHaveBeenCalledWith('post-1', { title: '수정 완료', content: postFixture.content })
  })
  it('labels the limited review feed, queries its place and never exposes delete for others', async () => {
    vi.mocked(api.fetchPlaceReviews).mockResolvedValue([reviewFixture, { ...reviewFixture, id: 'other-review', contents: '다른 여행자의 후기' }])
    const user = userEvent.setup()
    render(<CommunityBoard />)
    await user.click(screen.getByRole('button', { name: '여행 리뷰' }))
    expect(await screen.findByText(reviewFixture.contents)).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: '내가 작성한 여행 리뷰' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '이 장소 리뷰 보기' }))
    expect(await screen.findByText('다른 여행자의 후기')).toBeInTheDocument()
    expect(api.fetchPlaceReviews).toHaveBeenCalledWith('place-1', expect.any(AbortSignal))
    expect(screen.getAllByRole('button', { name: '리뷰 삭제' })).toHaveLength(1)
  })
  it('shows a neutral image fallback after remote photo failure', () => {
    render(<CommunityPhoto title="여행 사진" url="https://example.com/photo.jpg" className="h-36" />)
    fireEvent.error(screen.getByRole('img', { name: '여행 사진' }))
    expect(screen.getByText('사진을 불러오지 못했어요')).toBeInTheDocument()
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
  })
})
