export const LOCATION_TARGET_ACCURACY_METERS = 100
export const LOCATION_MAX_USABLE_ACCURACY_METERS = 1_000
export const LOCATION_WEATHER_MAX_ACCURACY_METERS = 5_000
export const LOCATION_QUALITY_SAMPLING_WINDOW_MS = 12_000
